version: "3.8"

services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: unless-stopped


  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wp-php
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - mariadb
    restart: unless-stopped

  ftp:
    build: requirements/bonus/ftp
    image: ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30100:30000-30100"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    restart: unless-stopped

volumes:
  wordpress_data:
  mariadb_data:

networks:
  my_network:
    driver: bridge