services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb
  #   ports:
  #     - "3306:3306"

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network

volumes:
  wordpress_data:

networks:
  my_network:
    driver: bridge
