version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    # environment:
    #   MYSQL_USER: /run/secrets/credentials
    #   MYSQL_PASSWORD: /run/secrets/db_password
    #   MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
    # secrets:
    #   - credentials
    #   - db_password
    #   - db_root_password
    networks:
      - my_network
    depends_on:
      - mariadb

volumes:
  wordpress_data:
  mariadb_data:

networks:
  my_network:
    driver: bridge

# secrets:
#   credentials:
#     external: true
#   db_password:
#     external: true
#   db_root_password:
#     external: true
