version: "3.9"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "8000:80"
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"