version: "3.8"

services:
  nginx:
    build: requirements/nginx
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    networks:
      - my_network
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wp-php
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - TITLE=${TITLE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
      - USER_EMAIL=${USER_EMAIL}
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - my_network
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped

  redis:
    build: requirements/bonus/redis
    image: redis:inception
    container_name: redis
    networks:
      - my_network
    restart: unless-stopped

  ftp:
    build: requirements/bonus/ftp
    image: ftp:inception
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30100:30000-30100"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    networks:
      - my_network
    restart: unless-stopped

  adminer:
    build: requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - my_network
    restart: unless-stopped

  website:
    build: requirements/bonus/website
    image: website:inception
    container_name: website
    ports:
      - "80:80"
    restart: unless-stopped

  portainer:
    build: requirements/bonus/portainer
    image: portainer:inception
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - PORTAINER_PASS=${PORTAINER_PASS}
    restart: unless-stopped

volumes:
  wordpress_data:
  mariadb_data:

networks:
  my_network:
    driver: bridge